config/routes.rb
Rails.application.routes.draw do

  # get '/auth/:provider', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  # Webhooks
  post 'pagerduty/incident', to: 'pager_duty#webhook', :defaults => { :format => 'json' }
  
  resources :sessions, only: [:create, :destroy]
  resources :home, only: [:show]

  resources :organizations, param: :slug do
    resources :blackboxes
    resources :users, only: [:new, :create, :show] do
      member do
        get :add_existing_user
        post :confirm_add
        get :confirm_email
      end
    end
  end

  root to: "home#show"
end

app/models/blackbox.rb
class Blackbox < ActiveRecord::Base
  belongs_to :organization
  has_many :incidents
  has_many :blackbox_involved_users
  has_many :involved_users, :through => :blackbox_involved_users, :source => :user
end

app/controllers/blackboxes_controller.rb
class BlackboxesController < ApplicationController
  include OrganizationSecurity
  before_action do 
    require_membership(params[:organization_slug], current_user)
  end
  
  def index
    @incidents = service.get_incidents
  end

  def show
    @blackbox = Blackbox.find(params[:id])
 end

  private

  def service
    org = get_current_org
    @service ||= IncidentManagementService.new(org.pagerduty_account, org.pagerduty_token)
  end

  def normalize_log_entries( log_entries )
    log_entries.map do |log|
      case log.type
      when 'assign'
        log.user = log.assigned_user
      when 'notify'
        log.user = {name: '', email: log.notification.address, avatar_url: ''}
      else
        if !log.agent.nil? && log.agent.type == 'user'
          log.user = log.agent
        elsif
          log.user = {name: 'todo: find name', email: '', avatar_url: ''}
          puts log
        end
      end
      log
    end
  end

  def combine_logs_and_notes( log_entries, notes )
    combined = log_entries.concat notes
    combined.compact!
    combined.sort_by{ |h| h.created_at }
  end

  private

  def get_current_org
    Organization.find_by(slug: params[:organization_slug])
  end

  def require_org_membership
    organization = get_current_org
    if organization.nil? 
      return false
    end
    organization.users.find( current_user )
  end

end

app/helpers/blackboxes_helper.rb
module BlackboxesHelper
end

app/views/blackboxes/index.html.erb
<ol>
  <% @incidents.each do |incident| %>
  <li><%= link_to incident.trigger_summary_data.subject , organization_incident_path(id: incident.id) %>
  <ul>
    <li><%= incident.incident_number %> | <a href="<%= incident.html_url%>"><%= incident.html_url%></a></li>
    <li><%= incident.status%> at <%= incident.last_status_change_on %></li>
  </ul>
<% end %>
</ol>

app/views/blackboxes/show.html.erb
<nav class="org z-depth-0">
  <div class="nav-wrapper">
    <div class="col s12 white">
      <%= link_to "Orgs", root_path, :class=>"breadcrumb" %>
      <%= link_to @blackbox.organization.name, organization_path(@blackbox.organization.slug), :class=>"breadcrumb" %>
      <a class="breadcrumb"><%= @blackbox.name %></a>
    </div>
  </div>
</nav>

<h3>Users Involved</h3>
<!-- Involved Users-->
<% @blackbox.involved_users.each do |usr| %>
  <div class="chip"><a href="mailto:<%= usr.email %>"><%= usr.full_name %></a></div>
<% end %>

<h3>Incident Log</h3>
<table>
  <thead>
    <tr>
      <th>Date/Time</th>
      <th>Action</th>
      <th>Actor</th>
  </thead>
  <tbody>
    <% @blackbox.incidents.first.incident_logs.each do |log| %>
      <tr>
        <td><%= log.created_at %></td>
        <td><%= log.action.capitalize %></td>
        <td>TODO: Add</td>
      </tr>
    <% end %>
  </tbody>
</table>