config/routes.rb
Rails.application.routes.draw do

  # get '/auth/:provider', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  # Webhooks
  post 'pagerduty/incident', to: 'pager_duty#webhook', :defaults => { :format => 'json' }
  
  resources :sessions, only: [:create, :destroy]
  resources :home, only: [:show]

  resources :organizations, param: :slug do
    resources :blackboxes
    resources :users, only: [:new, :create, :show] do
      member do
        get :add_existing_user
        post :confirm_add
        get :confirm_email
      end
    end
  end

  root to: "home#show"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.erb
<h3 class="page-title">Dashboard</h3>

<% if current_user && current_user.has_zero_organizations? %>
  <p>
    It doesn't look like you're a member of any organizations. <b>I'll walk you through how to start using blkbox.</b>
  </p>
  <%= button_to "Create Organization", new_organization_path, method: :get, class: "background-green waves-effect waves-light btn" %>
<% elsif current_user %>
  <table>
    <thead>
      <tr>
          <% if current_user.has_more_than_one_org? %>
            <th data-field="organization-name">Organizations</th>
          <% else %>
            <th data-field="organization-name">Organization</th>
          <% end %>
      </tr>
    </thead>

    <tbody>
      <% current_user.organizations.each do |org| %>
        <tr>
          <td><%= link_to org.name, organization_path(slug: org.slug) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= button_to "Create New Organization", new_organization_path, method: :get, class: "right white-text background-green waves-effect waves-light btn" %>

<% end %>