config/routes.rb
Rails.application.routes.draw do

  # get '/auth/:provider', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  # Webhooks
  post 'pagerduty/incident', to: 'pager_duty#webhook', :defaults => { :format => 'json' }
  
  resources :sessions, only: [:create, :destroy]
  resources :home, only: [:show]

  resources :organizations, param: :slug do
    resources :blackboxes
    resources :users, only: [:new, :create, :show] do
      member do
        get :add_existing_user
        post :confirm_add
        get :confirm_email
      end
    end
  end

  root to: "home#show"
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  extend AttrEncrypted
  validates :name, presence: true,
                   uniqueness: true
  validates :pagerduty_account, presence: true
  validates :pagerduty_token, presence: true

  attr_encrypted :pagerduty_account, key: ENV['ENCRYPTION_KEY'], encode: true
  attr_encrypted :pagerduty_token, key: ENV['ENCRYPTION_KEY'], encode: true

  has_many :organization_users
  has_many :users, through: :organization_users
  has_many :blackboxes
end

app/controllers/organizations/base_controller.rb
class Organizations::BaseController < ApplicationController


end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  include OrganizationSecurity
  before_action except: [:new, :create] do
    require_membership(params[:slug], current_user)
  end

  def new
    @organization = current_user.organizations.new
  end

  def create
    @organization = current_user.organizations.new(organization_params)
    @organization.slug = @organization.name.parameterize
    if @organization.save
      current_user.organizations << @organization
      current_user.organization_users.find(@organization).update!(user_role: 1)
      flash[:success] = "#{@organization.name} has been created."
      redirect_to root_path
    else
      flash.now[:error] = @organization.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def show
    @organization = Organization.find_by(slug: params[:slug])
    @blackboxes = @organization.blackboxes
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :pagerduty_account, :pagerduty_token, :slug)
  end

end

app/helpers/organization_helper.rb
module OrganizationHelper
end

app/views/organizations/new.html.erb
<h3 class="page-title">Create Organization</h3>
<%= form_for @organization, url: organizations_path do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :pagerduty_account, "Pagerduty Account Name" %>
    <%= f.text_field :pagerduty_account %>
  </div>
  <div class="form-group">
    <%= f.label :pagerduty_token, "Pagerduty API Token" %>
    <%= f.text_field :pagerduty_token %>
  </div>
  <%= f.submit "Create Organization", class: "right background-green waves-effect waves-light btn" %>
<% end %>

app/views/organizations/show.html.erb
<nav class="org z-depth-0">
  <div class="nav-wrapper">
    <div class="col s12 white">
      <%= link_to "Orgs", root_path, :class=>"breadcrumb" %>
      <%= link_to @organization.name, organization_path, :class=>"breadcrumb" %>
    </div>
  </div>
</nav>

<%# <h2 class="page-title"><%= @organization.name %1> Dashboard</h2> %>
<div class="row">
  <div class="col s8">
    <h3>BlkBoxes</h3>
    <table>
      <thead>
        <tr>
          <th data-field="id">Name</th>
          <th data-field="start-at">Started</th>
          <th data-field="update-at">Updated</th>
        </tr>
      </thead>

      <tbody>
        <% @blackboxes.each do |bb| %>
          <tr>
            <td><%= link_to bb.name, organization_blackbox_path( bb.organization.slug, bb.id ) %></td>
            <td><%= bb.created_at %></td>
            <td><%= bb.updated_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col s4">
    <% if owner? %>
      <p>
      It sure is lonely in here. Invite some team members. <b>I'll walk you through how to start using blkbox.</b>
      </p>
      <%= button_to "Add a User", new_organization_user_path(organization_slug: @organization.slug), method: :get, class: "background-green waves-effect waves-light btn" %>
    <% else %>
      stuff should go here for none owners
    <% end %>
  </div>
</div>